namespace: tenant-b

resources:
  - ../../base

patches:
  - target:
      kind: RoleBinding
      name: tenant-admin-rolebinding
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: tenant-b-admin@mydomain.com
  - target:
      kind: RepoSync
      name: repo-sync
    patch: |-
      - op: replace
        path: /spec/git/repo
        value: https://github.com/ejmadkins/acm-multi-repo-tenant-b.git
