apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: image-serve
build:
  artifacts:
    - image: europe-west2-docker.pkg.dev/PROJECT-INSERT/image-serve/container-day-image
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  googleCloudBuild:
    projectId: PROJECT-INSERT
deploy:
  kubectl:
    manifests:
      - k8s/*
