apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPStorageLocationConstraintV1
metadata:
  name: europe-only
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups:
          - storage.cnrm.cloud.google.com
        kinds:
          - StorageBucket
  parameters:
    locations:
      - europe-west1
      - europe-west2
