namespace: tenant-a

resources:
  - ../../base

patches:
  - target:
      kind: RoleBinding
      name: tenant-sync
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: ns-reconciler-tenant-a
  - target:
      kind: Namespace
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: tenant-a
      - op: replace
        path: /metadata/annotations/cnrm.cloud.google.com~1project-id
        value: ejmadkins-cday-krm-github
  - target:
      kind: RepoSync
      name: repo-sync
    patch: |-
      - op: replace
        path: /spec/git/repo
        value: https://github.com/edadkins-google/acm-multi-repo-tenant-a.git
  - target:
      kind: ServiceAccount
      name: ksa
    patch: |-
      - op: replace
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: tenant-a@ejmadkins-cday-krm-github.iam.gserviceaccount.com
  - target:
      kind: IAMPolicy
      name: gsa-wi
    patch: |-
      - op: replace
        path: /spec/resourceRef/namespace
        value: tenant-a
      - op: replace
        path: /spec/bindings/0/members/0
        value: serviceAccount:ejmadkins-cday-krm-github.svc.id.goog[tenant-a/ksa]
