apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: cnrmsa-cluster-krm-demo@PROJECT-INSERT.iam.gserviceaccount.com
  mode: cluster
