apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.70.0
    iam.gke.io/gcp-service-account: image-serve-cluster-krm-demo@PROJECT-INSERT.iam.gserviceaccount.com
